IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'JUNDIAIGRAPH_TC')
BEGIN
    CREATE DATABASE JUNDIAIGRAPH_TC;
END
GO

USE JUNDIAIGRAPH_TC;
GO

CREATE TABLE dbo.COORDINATE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    AXIS_X INT NOT NULL,
    AXIS_Y INT NOT NULL
);
GO

CREATE TABLE dbo.NEIGHBORHOOD (
    NAME NVARCHAR(50) PRIMARY KEY,
    COORDINATE_ID INT NOT NULL,
    FOREIGN KEY (COORDINATE_ID) REFERENCES COORDINATE(ID)
);
GO

CREATE TABLE dbo.NEIGHBORHOOD_PATH (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FROM_ID NVARCHAR(50) NOT NULL, 
    TO_ID NVARCHAR(50) NOT NULL,
    DISTANCE INT NOT NULL,
    TRAFFIC INT NOT NULL, 
    MAX_SPEED INT NOT NULL,
    FOREIGN KEY (FROM_ID) REFERENCES NEIGHBORHOOD(NAME),
    FOREIGN KEY (TO_ID) REFERENCES NEIGHBORHOOD(NAME)
);
GO

CREATE TABLE dbo.TRANSPORT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MODELO NVARCHAR(50) NOT NULL,
    MAX_SPEED INT NOT NULL
);
GO

CREATE INDEX COORDINATE_IDX ON COORDINATE(ID);
GO

CREATE INDEX NEIGHBORHOOD_IDX ON NEIGHBORHOOD(NAME);
GO

CREATE INDEX NEIGHBORHOOD_PATH_IDX ON NEIGHBORHOOD_PATH(ID);
GO

CREATE INDEX NEIGHBORHOOD_PATH_FROM_TO_IDX ON NEIGHBORHOOD_PATH(FROM_ID, TO_ID);
GO

CREATE OR ALTER VIEW dbo.NEIGHBORHOODVIEW 
WITH SCHEMABINDING
AS
SELECT 
    N.NAME,
    C.AXIS_X,
    C.AXIS_Y
FROM 
    dbo.NEIGHBORHOOD N
INNER JOIN 
    dbo.COORDINATE C ON N.COORDINATE_ID = C.ID;
GO

CREATE UNIQUE CLUSTERED INDEX NEIGHBORHOODVIEW_NAME_IDX
ON dbo.NEIGHBORHOODVIEW (NAME);