USE JUNDIAIGRAPH_TC;
GO

-- Serra do Japi
EXEC INSERTNEIGHBORHOODPATH N'Serra do Japi', N'Castanho', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Serra do Japi', N'Vila Rami', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Serra do Japi', N'Malota', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Serra do Japi', N'Alvorada', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Serra do Japi', N'Eloy Chaves', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Serra do Japi', N'Medeiros', 0;
GO

-- Castanho
EXEC INSERTNEIGHBORHOODPATH N'Castanho', N'Serra do Japi', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Castanho', N'Vila Rami', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Castanho', N'Vila Arens', 0;
GO

-- Vila Rami
EXEC INSERTNEIGHBORHOODPATH N'Vila Rami', N'Serra do Japi', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Vila Rami', N'Malota', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Vila Rami', N'Vila Arens', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Vila Rami', N'Castanho', 0;
GO

-- Vila Arens
EXEC INSERTNEIGHBORHOODPATH N'Vila Arens', N'Centro', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Vila Arens', N'Vila Rami', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Vila Arens', N'Colônia', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Vila Arens', N'Malota', 0;
GO

-- Malota
EXEC INSERTNEIGHBORHOODPATH N'Malota', N'Serra do Japi', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Malota', N'Alvorada', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Malota', N'Anhangabaú', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Malota', N'Vila Rami', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Malota', N'Vila Arens', 0;
GO

-- Anhangabaú
EXEC INSERTNEIGHBORHOODPATH N'Anhangabaú', N'Malota', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Anhangabaú', N'Alvorada', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Anhangabaú', N'Retiro', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Anhangabaú', N'Centro', 0;
GO
GO
EXEC INSERTNEIGHBORHOODPATH N'Anhangabaú', N'Vila Arens', 0;
GO

-- Alvorada
EXEC INSERTNEIGHBORHOODPATH N'Alvorada', N'Eloy Chaves', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Alvorada', N'Distrito Industrial', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Alvorada', N'Retiro', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Alvorada', N'Anhangabaú', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Alvorada', N'Malota', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Alvorada', N'Serra do Japi', 0;
GO

-- Retiro
EXEC INSERTNEIGHBORHOODPATH N'Retiro', N'Hortolândia', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Retiro', N'Alvorada', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Retiro', N'Centro', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Retiro', N'Anhangabaú', 0;
GO

-- Centro
EXEC INSERTNEIGHBORHOODPATH N'Centro', N'Retiro', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Centro', N'São Camilo', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Centro', N'Vila Arens', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Centro', N'Anhangabaú', 0;
GO

-- Eloy Chaves
EXEC INSERTNEIGHBORHOODPATH N'Eloy Chaves', N'Serra do Japi', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Eloy Chaves', N'Medeiros', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Eloy Chaves', N'Fazenda Grande', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Eloy Chaves', N'Distrito Industrial', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Eloy Chaves', N'Alvorada', 0;
GO

-- Medeiros
EXEC INSERTNEIGHBORHOODPATH N'Medeiros', N'Novo Horizonte', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Medeiros', N'Fazenda Grande', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Medeiros', N'Eloy Chaves', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Medeiros', N'Serra do Japi', 0;
GO

-- Fazenda Grande
EXEC INSERTNEIGHBORHOODPATH N'Fazenda Grande', N'Novo Horizonte', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Fazenda Grande', N'Água Doce', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Fazenda Grande', N'Distrito Industrial', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Fazenda Grande', N'Eloy Chaves', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Fazenda Grande', N'Medeiros', 0;
GO

-- Novo Horizonte
EXEC INSERTNEIGHBORHOODPATH N'Novo Horizonte', N'Fernandes', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Novo Horizonte', N'Água Doce', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Novo Horizonte', N'Fazenda Grande', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Novo Horizonte', N'Medeiros', 0;
GO

-- Distrito Industrial
EXEC INSERTNEIGHBORHOODPATH N'Distrito Industrial', N'Fazenda Grande', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Distrito Industrial', N'Eloy Chaves', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Distrito Industrial', N'Alvorada', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Distrito Industrial', N'Hortolândia', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Distrito Industrial', N'CECAP', 0;
GO

-- Agua Doce
EXEC INSERTNEIGHBORHOODPATH N'Água Doce', N'Fazenda Grande', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Água Doce', N'Novo Horizonte', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Água Doce', N'Fernandes', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Água Doce', N'Distrito Industrial', 0;
GO

-- CECAP
EXEC INSERTNEIGHBORHOODPATH N'CECAP', N'Fernandes', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'CECAP', N'Distrito Industrial', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'CECAP', N'Currupira', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'CECAP', N'Parque Centenário', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'CECAP', N'Hortolândia', 0;
GO

-- Hortolândia
EXEC INSERTNEIGHBORHOODPATH N'Hortolândia', N'Retiro', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Hortolândia', N'Distrito Industrial', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Hortolândia', N'CECAP', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Hortolândia', N'Parque Centenário', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Hortolândia', N'São Camilo', 0;
GO

-- Fernandes
EXEC INSERTNEIGHBORHOODPATH N'Fernandes', N'Novo Horizonte', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Fernandes', N'Currupira', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Fernandes', N'CECAP', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Fernandes', N'Água Doce', 0;
GO

-- Parque Centenário
EXEC INSERTNEIGHBORHOODPATH N'Parque Centenário', N'CECAP', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Parque Centenário', N'Currupira', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Parque Centenário', N'Hortolândia', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Parque Centenário', N'Jundiaí Mirim', 0;
GO

-- Currupira
EXEC INSERTNEIGHBORHOODPATH N'Currupira', N'Fernandes', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Currupira', N'CECAP', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Currupira', N'Parque Centenário', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Currupira', N'Rio Acima', 0;
GO

-- Rio Acima
EXEC INSERTNEIGHBORHOODPATH N'Rio Acima', N'Currupira', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Rio Acima', N'Jundiaí Mirim', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Rio Acima', N'Roseira', 0;
GO

-- Jundiaí Mirim
EXEC INSERTNEIGHBORHOODPATH N'Jundiaí Mirim', N'Parque Centenário', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Jundiaí Mirim', N'Rio Acima', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Jundiaí Mirim', N'Caxambu', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Jundiaí Mirim', N'São Camilo', 0;
GO

-- Roseira
EXEC INSERTNEIGHBORHOODPATH N'Roseira', N'Rio Acima', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Roseira', N'Caxambu', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Roseira', N'Campo Verde', 0;
GO

-- Caxambu
EXEC INSERTNEIGHBORHOODPATH N'Caxambu', N'Roseira', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Caxambu', N'São Camilo', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Caxambu', N'Jundiaí Mirim', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Caxambu', N'Campo Verde', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Caxambu', N'Colônia', 0;
GO

-- Campo Verde
EXEC INSERTNEIGHBORHOODPATH N'Campo Verde', N'Colônia', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Campo Verde', N'Caxambu', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Campo Verde', N'Roseira', 0;
GO

-- Colônia
EXEC INSERTNEIGHBORHOODPATH N'Colônia', N'São Camilo', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Colônia', N'Campo Verde', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Colônia', N'Vila Arens', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'Colônia', N'Centro', 0;
GO

-- São Camilo
EXEC INSERTNEIGHBORHOODPATH N'São Camilo', N'Centro', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'São Camilo', N'Hortolândia', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'São Camilo', N'Jundiaí Mirim', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'São Camilo', N'Caxambu', 0;
GO
EXEC INSERTNEIGHBORHOODPATH N'São Camilo', N'Colônia', 0;