USE JUNDIAIGRAPH_TC;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Anhangabaú', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Centro', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Chácara Urbana', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Gramadão', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Malota', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Moisés', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Samambaia', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vianelo', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vila Arens', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vila Municipal', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vila Rio Branco', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Agapeama', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Bonfiglioli', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Jardim Castanho', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Jardim do Lago', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vila Militar', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vila Progresso', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vila Rami', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Maringá', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Santa Gertrudes', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Caxambu', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Colônia', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Jardim Pacaembu', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Jundiaí Mirim', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Parque Residencial Jundiaí II', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Nambi', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Ponte São João', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'São Camilo', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Tamoio', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Tarumã', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Jardim Vale Azul', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Aeroporto', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Água Doce', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Alvorada', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Casa Branca', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Distrito Industrial', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Eloy Chaves', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Ermida', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Fazenda Grande', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Novo Horizonte', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Parque Industrial', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Ponte', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Rios das Pedras', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Tulipas', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'CECAP', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Engodadouro', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Honto Florestal', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Hortolândia', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Parque Centenário', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Torres de São José', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Bom Jardim', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Jardim Campo Verde', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Champirra', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Currupira', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Fazenda Conceição', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Fernandes', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Ivoturucaia', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Nova Odessa', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Pinheirinho', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Ponta Alta', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'São José da Pedra Santa', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Rio Acima', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Roseira', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Toca', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Traviú', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Cristais', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Pracatú', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Serra do Japi', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Terra Nova', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Tijuco Preto', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Retiro', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Mato Dentro', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Jardim Botânico', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Medeiros', @AXIS_X = 0, @AXIS_Y = 0;