USE JUNDIAIGRAPH_TC;
GO

EXEC INSERTTRANSPORT @MODEL = 'Carro', @MAX_SPEED = 60;
GO

EXEC INSERTTRANSPORT @MODEL = 'Motocicleta', @MAX_SPEED = 80;
GO

EXEC INSERTTRANSPORT @MODEL = 'Ônibus', @MAX_SPEED = 50;
GO

EXEC INSERTTRANSPORT @MODEL = 'Caminhão', @MAX_SPEED = 40;
GO

EXEC INSERTTRANSPORT @MODEL = 'Bicicleta', @MAX_SPEED = 30;