USE JUNDIAIGRAPH_TC;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Anhangabaú', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Centro', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Malota', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vila Arens', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Castanho', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Vila Rami', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Caxambu', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Colônia', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Jundiaí Mirim', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'São Camilo', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Água Doce', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Alvorada', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Distrito Industrial', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Eloy Chaves', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Fazenda Grande', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Novo Horizonte', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'CECAP', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Hortolândia', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Parque Centenário', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Campo Verde', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Currupira', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Fernandes', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Rio Acima', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Roseira', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Serra do Japi', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Retiro', @AXIS_X = 0, @AXIS_Y = 0;
GO

EXEC INSERTNEIGHBORHOOD @NAME = N'Medeiros', @AXIS_X = 0, @AXIS_Y = 0;