USE JUNDIAIGRAPH_TC;
GO

EXEC INSERTTRANSPORT @NAME = 'Carro compacto', @MAX_SPEED = 60;
GO

EXEC INSERTTRANSPORT @NAME = 'Motocicleta', @MAX_SPEED = 80;
GO

EXEC INSERTTRANSPORT @NAME = 'Ônibus', @MAX_SPEED = 50;
GO

EXEC INSERTTRANSPORT @NAME = 'Caminhão', @MAX_SPEED = 40;
GO

EXEC INSERTTRANSPORT @NAME = 'Bicicleta', @MAX_SPEED = 30;