USE JUNDIAIGRAPH_TC;
GO

--INSERT, UPDATE, DELETE

CREATE OR ALTER PROCEDURE INSERTNEIGHBORHOOD
    @NAME NVARCHAR(50),
    @AXIS_X INT,
    @AXIS_Y INT
AS
BEGIN
    INSERT INTO NEIGHBORHOOD (NAME, AXIS_X, AXIS_Y)
    VALUES (@NAME, @AXIS_X, @AXIS_Y);
END;
GO

--CREATE OR ALTER PROCEDURE UPDATENEIGHBORHOOD
--    @ID INT,
--    @NAME NVARCHAR(50),
--    @AXIS_X INT,
--    @AXIS_Y INT
--AS
--BEGIN
--    DECLARE @COORDINATE_ID INT;

--    SELECT @COORDINATE_ID = COORDINATE_ID
--    FROM NEIGHBORHOOD
--    WHERE ID = @ID;

--    UPDATE COORDINATE
--    SET AXIS_X = @AXIS_X,
--        AXIS_Y = @AXIS_Y
--    WHERE ID = @COORDINATE_ID;

--    UPDATE NEIGHBORHOOD
--    SET NAME = @NAME
--    WHERE ID = @ID;
--END;
--GO

--CREATE OR ALTER PROCEDURE DELETENEIGHBORHOOD
--    @ID INT
--AS
--BEGIN
--    DELETE FROM NEIGHBORHOOD WHERE ID = @ID;
--END
--GO

--CREATE OR ALTER PROCEDURE GETNEIGHBORHOOD
--    @NAME NVARCHAR(50) = NULL
--AS
--BEGIN
--    IF @NAME IS NULL
--        SELECT * FROM NEIGHBORHOODVIEW;
--    ELSE
--        SELECT TOP 1 * FROM NEIGHBORHOODVIEW WHERE NAME = @NAME;
--END;
--GO

CREATE OR ALTER PROCEDURE INSERTNEIGHBORHOODPATH
    @FROM_ID NVARCHAR(50),
    @TO_ID NVARCHAR(50),
    @DISTANCE INT
AS
BEGIN
    INSERT INTO NEIGHBORHOOD_PATH (FROM_ID, TO_ID, DISTANCE)
    VALUES (@FROM_ID, @TO_ID, @DISTANCE);
END;
GO

--CREATE OR ALTER PROCEDURE UPDATENEIGHBORHOODPATH
--    @ID INT,
--    @FROM_ID INT,
--    @TO_ID INT,
--    @DISTANCE DECIMAL(10,2),
--    @TRAFFIC INT,
--    @MAX_SPEED INT
--AS
--BEGIN
--    UPDATE NEIGHBORHOOD_PATH
--    SET FROM_ID = @FROM_ID, TO_ID = @TO_ID,
--        DISTANCE = @DISTANCE, TRAFFIC = @TRAFFIC, MAX_SPEED = @MAX_SPEED
--    WHERE ID = @ID;
--END;
--GO

--CREATE OR ALTER PROCEDURE DELETENEIGHBORHOODPATH
--    @ID INT
--AS
--BEGIN
--    DELETE FROM NEIGHBORHOOD_PATH WHERE ID = @ID;
--END;
--GO

--CREATE OR ALTER PROCEDURE INSERTTRANSPORT
--    @MODEL NVARCHAR(50),
--    @MAX_SPEED INT
--AS
--BEGIN
--    INSERT INTO TRANSPORT (MODEL, MAX_SPEED)
--    VALUES (@MODEL, @MAX_SPEED);
--END;
--GO

--CREATE OR ALTER PROCEDURE UPDATETRANSPORT
--    @ID INT,
--    @MODEL NVARCHAR(50),
--    @MAX_SPEED INT
--AS
--BEGIN
--    UPDATE TRANSPORT
--    SET MODEL = @MODEL, MAX_SPEED = @MAX_SPEED
--    WHERE ID = @ID;
--END;
--GO

--CREATE OR ALTER PROCEDURE DELETETRANSPORT
--    @ID INT
--AS
--BEGIN
--    DELETE FROM TRANSPORT WHERE ID = @ID;
--END;
--GO

--GET

--CREATE OR ALTER PROCEDURE GETTRANSPORT
--    @ID INT = NULL
--AS
--BEGIN
--    IF @ID IS NULL
--        SELECT * FROM TRANSPORT;
--    ELSE
--        SELECT TOP 1 * FROM TRANSPORT WHERE ID = @ID;
--END;
--GO

CREATE OR ALTER PROCEDURE GETNEIGHBORHOOD
    @NAME NVARCHAR(50) = NULL
AS
BEGIN
    IF @NAME IS NULL
        SELECT * FROM NEIGHBORHOOD WITH (INDEX(NEIGHBORHOOD_IDX));
    ELSE
        SELECT TOP 1 * FROM NEIGHBORHOOD WITH (INDEX(NEIGHBORHOOD_IDX))
		WHERE 
			NAME = @NAME;
END;
GO

CREATE OR ALTER PROCEDURE GETNEIGHBORHOODPATH
    @FROM_ID NVARCHAR(50) = NULL,
	@TO_ID NVARCHAR(50) = NULL
AS
BEGIN
    IF @FROM_ID IS NULL OR @TO_ID IS NULL
        SELECT * FROM NEIGHBORHOOD_PATH WITH (INDEX(NEIGHBORHOOD_PATH_FROM_TO_IDX));
    ELSE
        SELECT TOP 1 * FROM NEIGHBORHOOD_PATH WITH (INDEX(NEIGHBORHOOD_PATH_FROM_TO_IDX))
		WHERE 
			FROM_ID = @FROM_ID
			AND TO_ID = @TO_ID;
END;
GO

--CREATE OR ALTER FUNCTION dbo.GETNEIGHBORHOOD_PATH(@VEHICLEMAXSPEED INT)
--RETURNS TABLE
--AS
--RETURN
--(
--    SELECT
--        FROM_ID,
--        TO_ID,
--        DISTANCE,
--        TRAFFIC,
--        MAX_SPEED,
--		CEILING(
--			(60.0 * DISTANCE / 
--				IIF(MAX_SPEED < @VEHICLEMAXSPEED, MAX_SPEED, @VEHICLEMAXSPEED)
--			) * (1 + TRAFFIC / 100.0)
--		) AS WEIGHT
--    FROM dbo.NEIGHBORHOOD_PATH
--);